spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: rootroot
    url: jdbc:mysql://localhost:3306/nttdata_taller5?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
